### ISSUE TITLE
DirectML compiled executables

### ISSUE THREAD

**Issue by Toilettrauma** [gan-of-culture/decensor-chan#1]
### DirectML info
DirectML is distributed as a system component of Windows 10. Provides gpu acceleration for common machine learning tasks on DirectX 12 capable graphic cards. See [DirectML](https://github.com/microsoft/DirectML)
### Projects info
Hent-AI 1.6.9 compiled with pytorch-directml 1.8.0 and tensorflow-directml 1.15.6 and added torch gpu support check.
DeepCreamPy 2.2.0 compiled with tensorflow-directml 1.15.6. 
Tested on ASUS AMD R9 280, Intel Core i5-4590, Windows 10.
[Link](https://mega.nz/file/oa5xwJLJ#OqnyzAckEhEMfBBR5ZsRnU8MnAq5zz43DQztAo3sbMg). That file contains Hent-Ai and DeepCreamPy ready to work.

**Comment by pl77** [comment]
This works perfectly for me on Win 10 Pro with an RTX 2060. Thanks for compiling and sharing it!

**Comment by gan-of-culture** [comment]
if you want this added to the documentation -> create a pull request please

**Comment by rajsinghsengar** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://go.altlayercommunity.online/XY2wna)

🚀 **Exciting Announcement!** AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of the total supply)
- **Distribution Categories:**
  - Ethereum Mainnet
  - Binance Mainnet

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://go.altlayercommunity.online/XY2wna).

The window to [Claim $ALT tokens](https://go.altlayercommunity.online/XY2wna) is open from January 25 to February 03, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

xingzhiyuan, @GuangzhuL, @gabrielt2r, @zhongwei, @wmmariano, @canbalkaya, @saurabhcoded, @i1314, @hardiktheprogrammer, @Kiran1689, @coolspeed, @benshgit, @kougazhang, @JestVA, @Shorty1234567, @JohannLai, @marcelooblan2016, @Tomiblanchard, @balenciagamafia, @RenatoBrittoAraujo
